# -*- coding: utf-8 -*-
"""projeto_algoritmo_de_auditoria_de_dados

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/135QPSXhloeuL3zMtFvkftN7S6E-yhUdd
"""

LIMITE_SEGURANCA = 10000.00

vd1 = float(input("Venda 1: "))
vd2 = float(input("Venda 2: "))
vd3 = float(input("Venda 3: "))

def analisar_vendas(v1, v2, v3):
    global LIMITE_SEGURANCA

    media = (v1 + v2 + v3) / 3

    if v1 > LIMITE_SEGURANCA or v2 > LIMITE_SEGURANCA or v3 > LIMITE_SEGURANCA:
        print("ALERTA: Venda acima do limite de segurança detectada!")
        decisao = input("GERENTE: Deseja aumentar o limite de segurança para validar as vendas? (s/n): ")
        if decisao == "s":
            novo_limite = float(input("Digite o novo valor do limite: "))
            LIMITE_SEGURANCA = novo_limite

    print("-" * 40)
    print(f"Venda 1: R$ {v1:.2f} - {type(v1)}")
    print(f"Venda 2: R$ {v2:.2f} - {type(v2)}")
    print(f"Venda 3: R$ {v3:.2f} - {type(v3)}")
    print(f"Média: R$ {media:.2f} - {type(media)}")
    print(f"Limite Segurança: R$ {LIMITE_SEGURANCA:.2f} - {type(LIMITE_SEGURANCA)}")
    print("-" * 40)

    if media > LIMITE_SEGURANCA:
        print("SISTEMA EM QUARENTENA")

    if v1 > media * 5 or v2 > media * 5 or v3 > media * 5:
        print("REVISÃO MANUAL NECESSÁRIA")

analisar_vendas(vd1, vd2, vd3)